# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.1.1

pipelines:
  default:
    - step:
        caches:
          - composer
        services:
          - mysql
        script:
          - apt-get update && apt-get install -y unzip mysql-client
          - docker-php-ext-install pdo pdo_mysql
          - docker-php-ext-enable pdo pdo_mysql
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - mysql -h 127.0.0.1 -u sw0rdfish_user -p sw0rdfish_password sw0rdfish < sw0rdfish.sql
          - vendor/bin/phpunit tests/

definitions:
  caches:
    composer: /usr/local/composer
  services:
    mysql:
      image: mysql
      environment:
        MYSQL_DATABASE: 'sw0rdfish'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USERNAME: 'sw0rdfish_user'
        MYSQL_PASSWORD: 'sw0rdfish_password'
