# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.1.1
options:
    max-time: 15

pipelines:
  default:
    - step:
        name: Build source
        caches:
          - composer
          - vendor
        script:
          - apt-get update && apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --filename=composer
          - ./composer install
        artifacts:
          - composer
          - composer.lock
    - step:
        name: Test suite for SQLite
        caches:
          - composer
          - vendor
        script:
          - apt-get update && apt-get install -y unzip sqlite3
          - echo "STARTING TESTS WITH sqlite"
          - cat sw0rdfish-sqlite.sql | sqlite3 sw0rdfish.db3
          - export DB_DRIVER=sqlite
          - ./test.sh
    - step:
        name: Test suite for MySql
        caches:
          - composer
          - vendor
        services:
          - mysql
        script:
          - apt-get update && apt-get install -y unzip mysql-client
          - docker-php-ext-install pdo pdo_mysql
          - docker-php-ext-enable pdo pdo_mysql
          - echo "STARTING TESTS WITH MYSQL"
          - mysql --host=127.0.0.1 --user=sw0rdfish_user --password=sw0rdfish_password sw0rdfish < sw0rdfish-mysql.sql
          - export DB_DRIVER=mysql
          - ./test.sh
    - step:
        name: Deploy to staging
        deployment: staging
        script:
          - ./deploy.sh
    - step:
        name: Deploy to production
        deployment: production
        trigger: manual
        script:
          - ./deploy.sh

definitions:
  caches:
    vendor: vendor/
  services:
    mysql:
      image: mysql
      environment:
        MYSQL_DATABASE: 'sw0rdfish'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'sw0rdfish_user'
        MYSQL_PASSWORD: 'sw0rdfish_password'
